In [9]:
import numpy as np
n=int(input())
pascal = np.zeros((n,n), dtype = int)
pascal[0,0] = pascal[1,0] = pascal [1,1] = 1
for i in range(2,n):
    for j in range(0,n):
        pascal[i,j] = pascal[i-1,j-1] + pascal[i-1,j]
print(pascal)

5
[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 2 1 0 0]
 [1 3 3 1 0]
 [1 4 6 4 1]]
